use super::SqlDialect;

/// SQL function names for completion.
///
/// This is the authoritative source. Lua `SQL_FUNCTIONS` (completion_data.lua) is
/// a fallback-only copy used when the Rust binary is unavailable.
/// See `test_lua_fallback_functions_are_subset` for drift detection.
pub fn known_functions() -> &'static [&'static str] {
    &[
        // String
        "CONCAT",
        "CONCAT_WS",
        "FORMAT",
        "INSTR",
        "LOCATE",
        "POSITION",
        "LEFT",
        "RIGHT",
        "SUBSTRING",
        "SUBSTR",
        "MID",
        "SUBSTRING_INDEX",
        "LENGTH",
        "CHAR_LENGTH",
        "CHARACTER_LENGTH",
        "OCTET_LENGTH",
        "BIT_LENGTH",
        "LOWER",
        "LCASE",
        "UPPER",
        "UCASE",
        "TRIM",
        "LTRIM",
        "RTRIM",
        "REPLACE",
        "REGEXP_REPLACE",
        "REGEXP_LIKE",
        "REGEXP_SUBSTR",
        "REGEXP_INSTR",
        "REPEAT",
        "REVERSE",
        "LPAD",
        "RPAD",
        "SPACE",
        "FIELD",
        "FIND_IN_SET",
        "ELT",
        "SOUNDEX",
        "ASCII",
        "ORD",
        "CHAR",
        "UNICODE",
        "UNHEX",
        "HEX",
        "QUOTE",
        "STRCMP",
        // Numeric / Math
        "ABS",
        "CEIL",
        "CEILING",
        "FLOOR",
        "ROUND",
        "TRUNCATE",
        "TRUNC",
        "RAND",
        "RANDOM",
        "POWER",
        "POW",
        "SQRT",
        "EXP",
        "LN",
        "LOG",
        "LOG2",
        "LOG10",
        "MOD",
        "SIGN",
        "PI",
        "DIV",
        "CRC32",
        "SIN",
        "COS",
        "TAN",
        "ASIN",
        "ACOS",
        "ATAN",
        "ATAN2",
        "RADIANS",
        "DEGREES",
        "GREATEST",
        "LEAST",
        // Aggregate / Window
        "COUNT",
        "SUM",
        "AVG",
        "MIN",
        "MAX",
        "GROUP_CONCAT",
        "STRING_AGG",
        "ARRAY_AGG",
        "STD",
        "STDDEV",
        "STDDEV_POP",
        "STDDEV_SAMP",
        "VAR_POP",
        "VAR_SAMP",
        "VARIANCE",
        "BIT_AND",
        "BIT_OR",
        "BIT_XOR",
        "ROW_NUMBER",
        "RANK",
        "DENSE_RANK",
        "NTILE",
        "LAG",
        "LEAD",
        "FIRST_VALUE",
        "LAST_VALUE",
        "NTH_VALUE",
        "CUME_DIST",
        "PERCENT_RANK",
        "PERCENTILE_CONT",
        "PERCENTILE_DISC",
        // Date / Time
        "NOW",
        "SYSDATE",
        "LOCALTIME",
        "LOCALTIMESTAMP",
        "UTC_DATE",
        "UTC_TIME",
        "UTC_TIMESTAMP",
        "CURDATE",
        "CURTIME",
        "YEAR",
        "MONTH",
        "DAY",
        "DAYOFMONTH",
        "DAYOFWEEK",
        "DAYOFYEAR",
        "WEEK",
        "WEEKDAY",
        "WEEKOFYEAR",
        "HOUR",
        "MINUTE",
        "SECOND",
        "MICROSECOND",
        "QUARTER",
        "LAST_DAY",
        "DATE_FORMAT",
        "TIME_FORMAT",
        "FROM_UNIXTIME",
        "UNIX_TIMESTAMP",
        "STR_TO_DATE",
        "TO_DAYS",
        "FROM_DAYS",
        "DATE_ADD",
        "DATE_SUB",
        "ADDDATE",
        "SUBDATE",
        "ADDTIME",
        "SUBTIME",
        "TIMEDIFF",
        "TIMESTAMPDIFF",
        "TIMESTAMPADD",
        "DATEDIFF",
        "EXTRACT",
        "DATE_PART",
        "MAKEDATE",
        "MAKETIME",
        "MAKE_DATE",
        "MAKE_TIME",
        "MAKE_TIMESTAMP",
        "CONVERT_TZ",
        "DATE_TRUNC",
        "TIME_TRUNC",
        "AGE",
        "ISFINITE",
        "JUSTIFY_DAYS",
        "JUSTIFY_HOURS",
        "JUSTIFY_INTERVAL",
        "CLOCK_TIMESTAMP",
        "STATEMENT_TIMESTAMP",
        "TRANSACTION_TIMESTAMP",
        // JSON
        "JSON_EXTRACT",
        "JSON_UNQUOTE",
        "JSON_KEYS",
        "JSON_CONTAINS",
        "JSON_CONTAINS_PATH",
        "JSON_SET",
        "JSON_INSERT",
        "JSON_REPLACE",
        "JSON_REMOVE",
        "JSON_ARRAY",
        "JSON_OBJECT",
        "JSON_ARRAY_APPEND",
        "JSON_MERGE",
        "JSON_MERGE_PATCH",
        "JSON_TYPE",
        "JSON_VALID",
        "JSON_DEPTH",
        "JSON_LENGTH",
        "JSON_QUOTE",
        "JSON_TABLE",
        "JSON_VALUE",
        "JSON_AGG",
        "JSON_OBJECT_AGG",
        "JSONB_BUILD_OBJECT",
        "JSONB_AGG",
        "JSONB_PRETTY",
        "JSONB_EXTRACT_PATH",
        "TO_JSON",
        "ROW_TO_JSON",
        // Conditional
        "COALESCE",
        "NULLIF",
        "IFNULL",
        "IF",
        // Type conversion
        "CAST",
        "CONVERT",
        "TRY_CAST",
        "TRY_CONVERT",
        "TO_CHAR",
        "TO_NUMBER",
        "TO_TIMESTAMP",
        // Security / Hash
        "MD5",
        "SHA1",
        "SHA2",
        "AES_ENCRYPT",
        "AES_DECRYPT",
        "RANDOM_BYTES",
        "UUID",
        "UUID_SHORT",
        // System / Info
        "VERSION",
        "DATABASE",
        "SCHEMA",
        "USER",
        "SESSION_USER",
        "SYSTEM_USER",
        "CONNECTION_ID",
        "ROW_COUNT",
        "FOUND_ROWS",
        "LAST_INSERT_ID",
        "CHARSET",
        "COLLATION",
        "CURRENT_SCHEMA",
        "CURRENT_SETTING",
        "SET_CONFIG",
        // Full-Text Search
        "MATCH",
        "AGAINST",
        // Postgres extras
        "UNNEST",
        "GENERATE_SERIES",
        "ARRAY",
        "ROW",
        "SETSEED",
        // MySQL extras
        "ANY_VALUE",
        "BENCHMARK",
        "GET_LOCK",
        "RELEASE_LOCK",
        "RELEASE_ALL_LOCKS",
        "IS_FREE_LOCK",
        "IS_USED_LOCK",
        "SLEEP",
        "VALUES",
        // SQLite extras
        "TOTAL",
        "TYPEOF",
        "LIKELY",
        "UNLIKELY",
        "LIKELIHOOD",
        "CHANGES",
        "TOTAL_CHANGES",
        "SQLITE_VERSION",
        "SQLITE_SOURCE_ID",
        "ZEROBLOB",
    ]
}

/// Return function names filtered by dialect.
pub fn known_functions_for_dialect(dialect: SqlDialect) -> Vec<&'static str> {
    let all = known_functions();
    match dialect {
        SqlDialect::Generic => all.to_vec(),
        SqlDialect::Postgres => all
            .iter()
            .copied()
            .filter(|f| !MYSQL_ONLY.contains(f) && !SQLITE_ONLY.contains(f))
            .collect(),
        SqlDialect::MySql => all
            .iter()
            .copied()
            .filter(|f| !PG_ONLY.contains(f) && !SQLITE_ONLY.contains(f))
            .collect(),
        SqlDialect::Sqlite => all
            .iter()
            .copied()
            .filter(|f| !MYSQL_ONLY.contains(f) && !PG_ONLY.contains(f))
            .collect(),
    }
}

static MYSQL_ONLY: &[&str] = &[
    // String (MySQL-specific variants)
    "INSTR",
    "LOCATE",
    "SUBSTRING_INDEX",
    "SUBSTR",
    "MID",
    "FIELD",
    "FIND_IN_SET",
    "ELT",
    "SOUNDEX",
    "ORD",
    "UNHEX",
    "HEX",
    "STRCMP",
    "SPACE",
    "CHAR",
    // Regexp (MySQL-specific)
    "REGEXP_REPLACE",
    "REGEXP_LIKE",
    "REGEXP_SUBSTR",
    "REGEXP_INSTR",
    // Numeric
    "CRC32",
    // Aggregate
    "GROUP_CONCAT",
    "BIT_AND",
    "BIT_OR",
    "BIT_XOR",
    // JSON (MySQL flavor)
    "JSON_KEYS",
    "JSON_CONTAINS",
    "JSON_CONTAINS_PATH",
    "JSON_SET",
    "JSON_INSERT",
    "JSON_REPLACE",
    "JSON_REMOVE",
    "JSON_MERGE",
    "JSON_MERGE_PATCH",
    "JSON_TYPE",
    "JSON_VALID",
    "JSON_DEPTH",
    "JSON_LENGTH",
    "JSON_QUOTE",
    "JSON_TABLE",
    "JSON_VALUE",
    "JSON_AGG",
    "JSON_OBJECT_AGG",
    // Date/time (MySQL-specific)
    "SYSDATE",
    "UTC_DATE",
    "UTC_TIME",
    "UTC_TIMESTAMP",
    "CURDATE",
    "CURTIME",
    "DAYOFWEEK",
    "DAYOFYEAR",
    "WEEKDAY",
    "WEEKOFYEAR",
    "MICROSECOND",
    "QUARTER",
    "LAST_DAY",
    "DATE_FORMAT",
    "TIME_FORMAT",
    "FROM_UNIXTIME",
    "UNIX_TIMESTAMP",
    "STR_TO_DATE",
    "TO_DAYS",
    "FROM_DAYS",
    "ADDDATE",
    "SUBDATE",
    "ADDTIME",
    "SUBTIME",
    "TIMEDIFF",
    "MAKEDATE",
    "MAKETIME",
    "CONVERT_TZ",
    // Conditional
    "IFNULL",
    "IF",
    // Security
    "AES_ENCRYPT",
    "AES_DECRYPT",
    "UUID_SHORT",
    // System
    "DATABASE",
    "CONNECTION_ID",
    "FOUND_ROWS",
    "LAST_INSERT_ID",
    "CHARSET",
    "COLLATION",
    // Full-text
    "MATCH",
    "AGAINST",
    // MySQL extras
    "ANY_VALUE",
    "BENCHMARK",
    "GET_LOCK",
    "RELEASE_LOCK",
    "RELEASE_ALL_LOCKS",
    "IS_FREE_LOCK",
    "IS_USED_LOCK",
    "SLEEP",
    "VALUES",
];

static PG_ONLY: &[&str] = &[
    // Aggregate
    "STRING_AGG",
    "ARRAY_AGG",
    // JSON (PG flavor)
    "JSONB_BUILD_OBJECT",
    "JSONB_AGG",
    "JSONB_PRETTY",
    "JSONB_EXTRACT_PATH",
    "TO_JSON",
    "ROW_TO_JSON",
    // Date/time (PG-specific)
    "AGE",
    "ISFINITE",
    "JUSTIFY_DAYS",
    "JUSTIFY_HOURS",
    "JUSTIFY_INTERVAL",
    "CLOCK_TIMESTAMP",
    "STATEMENT_TIMESTAMP",
    "TRANSACTION_TIMESTAMP",
    "DATE_TRUNC",
    "TIME_TRUNC",
    "MAKE_DATE",
    "MAKE_TIME",
    "MAKE_TIMESTAMP",
    "DATE_PART",
    // Type conversion
    "TRY_CAST",
    "TRY_CONVERT",
    "TO_CHAR",
    "TO_NUMBER",
    "TO_TIMESTAMP",
    // System
    "CURRENT_SETTING",
    "SET_CONFIG",
    // PG extras
    "UNNEST",
    "GENERATE_SERIES",
    "ARRAY",
    "ROW",
    "SETSEED",
];

static SQLITE_ONLY: &[&str] = &[
    "TOTAL",
    "TYPEOF",
    "LIKELY",
    "UNLIKELY",
    "LIKELIHOOD",
    "CHANGES",
    "TOTAL_CHANGES",
    "SQLITE_VERSION",
    "SQLITE_SOURCE_ID",
    "ZEROBLOB",
];

#[cfg(test)]
mod tests {
    use super::*;

    /// Drift check: every function in Lua's fallback SQL_FUNCTIONS must exist
    /// in Rust's known_functions(). Snapshot of completion_data.lua.
    /// When adding functions to Lua, add them to Rust first.
    #[test]
    fn test_lua_fallback_functions_are_subset() {
        let lua_functions: &[&str] = &[
            "CONCAT",
            "CONCAT_WS",
            "FORMAT",
            "INSTR",
            "LOCATE",
            "POSITION",
            "LEFT",
            "RIGHT",
            "SUBSTRING",
            "SUBSTR",
            "MID",
            "SUBSTRING_INDEX",
            "LENGTH",
            "CHAR_LENGTH",
            "CHARACTER_LENGTH",
            "OCTET_LENGTH",
            "BIT_LENGTH",
            "LOWER",
            "LCASE",
            "UPPER",
            "UCASE",
            "TRIM",
            "LTRIM",
            "RTRIM",
            "REPLACE",
            "REGEXP_REPLACE",
            "REGEXP_LIKE",
            "REGEXP_SUBSTR",
            "REGEXP_INSTR",
            "REPEAT",
            "REVERSE",
            "LPAD",
            "RPAD",
            "SPACE",
            "FIELD",
            "FIND_IN_SET",
            "ELT",
            "SOUNDEX",
            "ASCII",
            "ORD",
            "CHAR",
            "UNICODE",
            "UNHEX",
            "HEX",
            "QUOTE",
            "STRCMP",
            "ABS",
            "CEIL",
            "CEILING",
            "FLOOR",
            "ROUND",
            "TRUNCATE",
            "TRUNC",
            "RAND",
            "RANDOM",
            "POWER",
            "POW",
            "SQRT",
            "EXP",
            "LN",
            "LOG",
            "LOG2",
            "LOG10",
            "MOD",
            "SIGN",
            "PI",
            "DIV",
            "CRC32",
            "SIN",
            "COS",
            "TAN",
            "ASIN",
            "ACOS",
            "ATAN",
            "ATAN2",
            "RADIANS",
            "DEGREES",
            "GREATEST",
            "LEAST",
            "COUNT",
            "SUM",
            "AVG",
            "MIN",
            "MAX",
            "GROUP_CONCAT",
            "STRING_AGG",
            "ARRAY_AGG",
            "STD",
            "STDDEV",
            "STDDEV_POP",
            "STDDEV_SAMP",
            "VAR_POP",
            "VAR_SAMP",
            "VARIANCE",
            "BIT_AND",
            "BIT_OR",
            "BIT_XOR",
            "ROW_NUMBER",
            "RANK",
            "DENSE_RANK",
            "NTILE",
            "LAG",
            "LEAD",
            "FIRST_VALUE",
            "LAST_VALUE",
            "NTH_VALUE",
            "CUME_DIST",
            "PERCENT_RANK",
            "PERCENTILE_CONT",
            "PERCENTILE_DISC",
            "NOW",
            "SYSDATE",
            "LOCALTIME",
            "LOCALTIMESTAMP",
            "UTC_DATE",
            "UTC_TIME",
            "UTC_TIMESTAMP",
            "CURDATE",
            "CURTIME",
            "YEAR",
            "MONTH",
            "DAY",
            "DAYOFMONTH",
            "DAYOFWEEK",
            "DAYOFYEAR",
            "WEEK",
            "WEEKDAY",
            "WEEKOFYEAR",
            "HOUR",
            "MINUTE",
            "SECOND",
            "MICROSECOND",
            "QUARTER",
            "LAST_DAY",
            "DATE_FORMAT",
            "TIME_FORMAT",
            "FROM_UNIXTIME",
            "UNIX_TIMESTAMP",
            "STR_TO_DATE",
            "TO_DAYS",
            "FROM_DAYS",
            "DATE_ADD",
            "DATE_SUB",
            "ADDDATE",
            "SUBDATE",
            "ADDTIME",
            "SUBTIME",
            "TIMEDIFF",
            "TIMESTAMPDIFF",
            "TIMESTAMPADD",
            "DATEDIFF",
            "EXTRACT",
            "DATE_PART",
            "MAKEDATE",
            "MAKETIME",
            "MAKE_DATE",
            "MAKE_TIME",
            "MAKE_TIMESTAMP",
            "CONVERT_TZ",
            "DATE_TRUNC",
            "TIME_TRUNC",
            "AGE",
            "ISFINITE",
            "JUSTIFY_DAYS",
            "JUSTIFY_HOURS",
            "JUSTIFY_INTERVAL",
            "CLOCK_TIMESTAMP",
            "STATEMENT_TIMESTAMP",
            "TRANSACTION_TIMESTAMP",
            "JSON_EXTRACT",
            "JSON_UNQUOTE",
            "JSON_KEYS",
            "JSON_CONTAINS",
            "JSON_CONTAINS_PATH",
            "JSON_SET",
            "JSON_INSERT",
            "JSON_REPLACE",
            "JSON_REMOVE",
            "JSON_ARRAY",
            "JSON_OBJECT",
            "JSON_ARRAY_APPEND",
            "JSON_MERGE",
            "JSON_MERGE_PATCH",
            "JSON_TYPE",
            "JSON_VALID",
            "JSON_DEPTH",
            "JSON_LENGTH",
            "JSON_QUOTE",
            "JSON_TABLE",
            "JSON_VALUE",
            "JSON_AGG",
            "JSON_OBJECT_AGG",
            "JSONB_BUILD_OBJECT",
            "JSONB_AGG",
            "JSONB_PRETTY",
            "JSONB_EXTRACT_PATH",
            "TO_JSON",
            "ROW_TO_JSON",
            "COALESCE",
            "NULLIF",
            "IFNULL",
            "IF",
            "CAST",
            "CONVERT",
            "TRY_CAST",
            "TRY_CONVERT",
            "TO_CHAR",
            "TO_NUMBER",
            "TO_TIMESTAMP",
            "MD5",
            "SHA1",
            "SHA2",
            "AES_ENCRYPT",
            "AES_DECRYPT",
            "RANDOM_BYTES",
            "UUID",
            "UUID_SHORT",
            "VERSION",
            "DATABASE",
            "SCHEMA",
            "USER",
            "SESSION_USER",
            "SYSTEM_USER",
            "CONNECTION_ID",
            "ROW_COUNT",
            "FOUND_ROWS",
            "LAST_INSERT_ID",
            "CHARSET",
            "COLLATION",
            "CURRENT_SCHEMA",
            "CURRENT_SETTING",
            "SET_CONFIG",
            "MATCH",
            "AGAINST",
            "UNNEST",
            "GENERATE_SERIES",
            "ARRAY",
            "ROW",
            "SETSEED",
            "ANY_VALUE",
            "BENCHMARK",
            "GET_LOCK",
            "RELEASE_LOCK",
            "RELEASE_ALL_LOCKS",
            "IS_FREE_LOCK",
            "IS_USED_LOCK",
            "SLEEP",
            "VALUES",
            "TOTAL",
            "TYPEOF",
            "LIKELY",
            "UNLIKELY",
            "LIKELIHOOD",
            "CHANGES",
            "TOTAL_CHANGES",
            "SQLITE_VERSION",
            "SQLITE_SOURCE_ID",
            "ZEROBLOB",
        ];
        let rust_funcs = known_functions();
        for &f in lua_functions {
            assert!(
                rust_funcs.contains(&f),
                "Lua fallback function '{}' is not in Rust's known_functions() — add it to functions.rs first",
                f,
            );
        }
    }

    #[test]
    fn test_dialect_filter_pg_excludes_mysql_only() {
        let pg = known_functions_for_dialect(crate::sql_context::SqlDialect::Postgres);
        assert!(
            !pg.contains(&"CRC32"),
            "Postgres should not include MySQL-only CRC32"
        );
        assert!(
            !pg.contains(&"GROUP_CONCAT"),
            "Postgres should not include MySQL-only GROUP_CONCAT"
        );
        assert!(
            pg.contains(&"STRING_AGG"),
            "Postgres should include PG-only STRING_AGG"
        );
        assert!(
            pg.contains(&"COUNT"),
            "Postgres should include generic COUNT"
        );
    }

    #[test]
    fn test_dialect_filter_mysql_excludes_pg_only() {
        let mysql = known_functions_for_dialect(crate::sql_context::SqlDialect::MySql);
        assert!(
            !mysql.contains(&"STRING_AGG"),
            "MySQL should not include PG-only STRING_AGG"
        );
        assert!(
            !mysql.contains(&"AGE"),
            "MySQL should not include PG-only AGE"
        );
        assert!(
            mysql.contains(&"GROUP_CONCAT"),
            "MySQL should include MySQL-only GROUP_CONCAT"
        );
        assert!(
            mysql.contains(&"COUNT"),
            "MySQL should include generic COUNT"
        );
    }

    #[test]
    fn test_dialect_filter_sqlite_excludes_both() {
        let sqlite = known_functions_for_dialect(crate::sql_context::SqlDialect::Sqlite);
        assert!(
            !sqlite.contains(&"CRC32"),
            "SQLite should not include MySQL-only CRC32"
        );
        assert!(
            !sqlite.contains(&"STRING_AGG"),
            "SQLite should not include PG-only STRING_AGG"
        );
        assert!(
            sqlite.contains(&"TOTAL"),
            "SQLite should include SQLite-only TOTAL"
        );
        assert!(
            sqlite.contains(&"COUNT"),
            "SQLite should include generic COUNT"
        );
    }

    #[test]
    fn test_dialect_filter_generic_returns_all() {
        let all = known_functions_for_dialect(crate::sql_context::SqlDialect::Generic);
        assert!(
            all.contains(&"CRC32"),
            "Generic should include MySQL-only CRC32"
        );
        assert!(
            all.contains(&"STRING_AGG"),
            "Generic should include PG-only STRING_AGG"
        );
        assert!(
            all.contains(&"TOTAL"),
            "Generic should include SQLite-only TOTAL"
        );
        assert_eq!(all.len(), known_functions().len());
    }
}
